my_string = input("Как вас зовут?: ")
print("Добрый день,", my_string)
print(len(my_string))

my_string1 = ("Добрый день, Данил, как ваши дела?")
print(my_string1.upper())
print(my_string1.lower())
print(my_string1.replace(" ", ""))
print(my_string1 [0])
print(my_string1 [-1])